/* Build-time generator (v2).
 *
 * Computes the pipeline output for the secret flag, splits it into a
 * directly-compared remainder and a discrete-log-gated scalar, and writes
 * generated/mono_data.h containing ONLY: the encrypted VM program, the
 * 26-byte remainder, and the 64-bit DLP target g^m mod p. The clear-text
 * flag -- and the scalar m itself -- never reach the shipped binary.
 *
 * Usage:  mono_gen <output-header-path>
 * Flag inner (exactly 32 chars) is taken from $MONO_FLAG_INNER, else default.
 *
 * ---------------------------------------------------------------------------
 * DESIGNER: change DEFAULT_INNER (or set $MONO_FLAG_INNER) to your own secret,
 * and keep this file / the repo private. Distribute only monolith.exe.
 * --------------------------------------------------------------------------- */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "spn.h"
#include "vm.h"
#include "bytecode_def.h"
#include "dlp.h"

/* Exactly 32 printable characters. */
#define DEFAULT_INNER "th3_v01d_5t4r3s_b4ck_1nt0_y0u!!!"

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <output-header>\n", argv[0]);
        return 2;
    }
    const char *inner = getenv("MONO_FLAG_INNER");
    if (!inner || !*inner) inner = DEFAULT_INNER;

    if (strlen(inner) != MONO_BLOCK) {
        fprintf(stderr,
            "error: flag inner must be exactly %d characters (got %zu)\n",
            MONO_BLOCK, strlen(inner));
        return 3;
    }

    uint8_t flag[MONO_BLOCK];
    memcpy(flag, inner, MONO_BLOCK);

    /* clear program -> tamper constant -> derived schedule (whitebox tables
     * are a runtime-only concern; the generator only needs the plain,
     * provably-equivalent reference pipeline to know the right answer). */
    uint8_t plain[MONO_BC_MAX];
    size_t  bclen = mono_bc_emit(plain);
    uint32_t tamper = mono_bc_tamper_plain(plain, bclen);

    mono_ctx ctx; mono_ctx_build(&ctx, tamper);

    /* intermediate = forward(flag); split into remainder + 48-bit scalar */
    uint8_t inter[MONO_BLOCK];
    memcpy(inter, flag, MONO_BLOCK);
    mono_forward(&ctx, inter);

    uint8_t remainder[MONO_REMAINDER_BYTES];
    memcpy(remainder, inter, MONO_REMAINDER_BYTES);

    uint64_t m = 0;
    for (int i = 0; i < MONO_SCALAR_BYTES; i++)
        m = (m << 8) | inter[MONO_REMAINDER_BYTES + i];
    if (m >= MONO_DLP_Q) {
        /* cannot happen with the shipped Q (2^48 < Q by construction), but
         * guard it explicitly rather than silently emit an ambiguous target */
        fprintf(stderr, "internal error: scalar %llu exceeds group order\n",
                (unsigned long long)m);
        return 6;
    }
    uint64_t target_r = modexp64(MONO_DLP_G, m, MONO_DLP_P);

    /* encrypt the program for embedding */
    uint8_t enc[MONO_BC_MAX];
    memcpy(enc, plain, bclen);
    mono_bc_crypt(enc, bclen);

    /* self-check: inverse(intermediate) must recover the flag, and the
     * remainder+scalar reconstruction must reproduce the same intermediate */
    uint8_t rebuilt[MONO_BLOCK];
    memcpy(rebuilt, remainder, MONO_REMAINDER_BYTES);
    for (int i = 0; i < MONO_SCALAR_BYTES; i++)
        rebuilt[MONO_REMAINDER_BYTES + i] = inter[MONO_REMAINDER_BYTES + i];
    if (memcmp(rebuilt, inter, MONO_BLOCK) != 0) {
        fprintf(stderr, "internal error: remainder/scalar split is lossy\n");
        return 4;
    }
    uint8_t chk[MONO_BLOCK];
    memcpy(chk, inter, MONO_BLOCK);
    mono_inverse(&ctx, chk);
    if (memcmp(chk, flag, MONO_BLOCK) != 0) {
        fprintf(stderr, "internal error: forward/inverse mismatch\n");
        return 4;
    }
    if (modexp64(MONO_DLP_G, m, MONO_DLP_P) != target_r) {
        fprintf(stderr, "internal error: DLP target self-check failed\n");
        return 4;
    }

    FILE *f = fopen(argv[1], "w");
    if (!f) { perror("fopen"); return 5; }

    fprintf(f,
        "/* AUTO-GENERATED by mono_gen -- do not edit.\n"
        " * Contains the encrypted VM program, the directly-compared\n"
        " * remainder, and the discrete-log target only -- never the flag,\n"
        " * never the scalar itself. */\n"
        "#ifndef MONO_DATA_H\n#define MONO_DATA_H\n#include <stdint.h>\n#include <stddef.h>\n\n");

    fprintf(f, "#define MONO_ENC_BC_LEN %zu\n", bclen);
    fprintf(f, "static const uint8_t MONO_ENC_BC[MONO_ENC_BC_LEN] = {\n");
    for (size_t i = 0; i < bclen; i++) {
        fprintf(f, "0x%02x,", enc[i]);
        if ((i % 12) == 11) fprintf(f, "\n");
    }
    fprintf(f, "\n};\n\n");

    fprintf(f, "static const uint8_t MONO_TARGET_REMAINDER[%d] = {\n", MONO_REMAINDER_BYTES);
    for (int i = 0; i < MONO_REMAINDER_BYTES; i++) {
        fprintf(f, "0x%02x,", remainder[i]);
        if ((i % 12) == 11) fprintf(f, "\n");
    }
    fprintf(f, "\n};\n\n");

    fprintf(f, "static const uint64_t MONO_TARGET_R = %lluULL;\n\n",
            (unsigned long long)target_r);
    fprintf(f, "#endif\n");
    fclose(f);

    fprintf(stderr, "mono_gen: wrote %s (program %zu bytes, tamper %08x)\n",
            argv[1], bclen, tamper);
    return 0;
}
